### ISSUE TITLE
using @module errors out

### ISSUE THREAD

**Issue by garytryan** [yui/yuidoc#234]
My code:
     /**
     \* Video Player
     *
     \* @module video
     */

Error Message:
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error:
TypeError: Cannot set property 'module' of undefined
    at DIGESTERS.class (/usr/local/lib/node_modules/yuidocjs/lib/docparser.js:502:33)
    at null.<anonymous> (/usr/local/lib/node_modules/yuidocjs/lib/docparser.js:1283:40)
    at Array.forEach (native)
    at Function.YArray.each.YArray.forEach.Lang._isNative.i (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/yui-nodejs/yui-nodejs.js:2281:20)
    at a (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:245)
    at e.each (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:1249)
    at Y.extend.processblock (/usr/local/lib/node_modules/yuidocjs/lib/docparser.js:1249:15)
    at null.<anonymous> (/usr/local/lib/node_modules/yuidocjs/lib/docparser.js:1341:26)
    at Array.forEach (native)
    at Function.YArray.each.YArray.forEach.Lang._isNative.i (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/yui-nodejs/yui-nodejs.js:2281:20)
    at a (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:245)
    at e.each (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:1249)
error: --------------------------------------------------------------------------
error: Node.js version: v0.10.25
error: YUI version: 3.14.1
error: YUIDoc version: 0.3.49
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------

**Comment by fooey** [comment]
looks like I started getting this exact same error, yuidoc has been working for me previously, but I haven't figured out what could have changed to break it

```
warn: Failed to extract port, setting to the default :3000
info: Starting YUIDoc@0.10.2 using YUI@3.18.1 with NodeJS@4.4.1
info: Scanning for yuidoc.json file.
warn: Skipping node_modules directory while scanning for yuidoc.json
info: Loading package.json data from: /sources/webapp-busy-time/package.json
info: Loading yuidoc.json data from: /sources/webapp-busy-time/yuidoc.json
info: Starting YUIDoc with the following options:
info: {"tabtospace":4,"linkNatives":true,"markdown":true,"paths":["./app"],"external":{"data":[{"base":"http://emberjs.com/api/","json":"http://builds.emberjs.com/release/ember-docs.json"},{"base":"http://emberjs.com/api/data/","json":"http://builds.emberjs.com/release/ember-data-docs.json"}]},"port":3000,"nocode":false,"server":true,"project":{"url":"/","logo":"http://localhost:4200/images/busybusylogo-gray.png","name":"busy-app","description":"busybusy web development project","version":"4.9.0-alpha.4"},"outdir":"./out","tabspace":"    "}
info: Scanning for yuidoc.json file.
warn: Skipping node_modules directory while scanning for yuidoc.json
info: Loading package.json data from: /sources/webapp-busy-time/package.json
info: Loading yuidoc.json data from: /sources/webapp-busy-time/yuidoc.json
warn: Fetching external data, this may take a minute
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: TypeError: Cannot set property 'module' of undefined
    at DIGESTERS.class (/usr/local/lib/node_modules/yuidocjs/lib/docparser.js:532:33)
    at null.<anonymous> (/usr/local/lib/node_modules/yuidocjs/lib/docparser.js:1388:40)
    at Array.forEach (native)
    at Function.YArray.each.YArray.forEach.Lang._isNative.i (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/yui-nodejs/yui-nodejs.js:2522:20)
    at a (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:245)
    at e.each (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:1249)
    at Y.extend.processblock (/usr/local/lib/node_modules/yuidocjs/lib/docparser.js:1354:15)
    at null.<anonymous> (/usr/local/lib/node_modules/yuidocjs/lib/docparser.js:1466:26)
    at Array.forEach (native)
    at Function.YArray.each.YArray.forEach.Lang._isNative.i (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/yui-nodejs/yui-nodejs.js:2522:20)
    at a (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:245)
    at e.each (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/oop/oop-min.js:1:1249)
error: --------------------------------------------------------------------------
error: Node.js version: v4.4.1
error: YUI version: 3.18.1
error: YUIDoc version: 0.10.2
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------
```
