### ISSUE TITLE
Error: EISDIR, illegal operation on a directory

### ISSUE THREAD

**Issue by krawalli** [yui/yuidoc#313]
~~~console
info: (yuidoc): Starting YUIDoc@0.5.0 using YUI@3.18.1 with NodeJS@0.10.33
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: 
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:487:19)
    at Object.fs.readSync (/usr/lib/node_modules/yuidocjs/node_modules/graceful-fs/polyfills.js:218:23)
    at Object.fs.readFileSync (fs.js:321:28)
    at Object.Y.Files.getJSON (/usr/lib/node_modules/yuidocjs/lib/files.js:426:34)
    at Object.Y.Project.init (/usr/lib/node_modules/yuidocjs/lib/project.js:23:35)
    at Object.<anonymous> (/usr/lib/node_modules/yuidocjs/lib/cli.js:24:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: --------------------------------------------------------------------------
error: Node.js version: v0.10.33
error: YUI version: 3.18.1
error: YUIDoc version: 0.5.0
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------
~~~

Seems it wants to read a directory as file, but unfortunatly it does not report which one

**Comment by okuryu** [comment]
`EISDIR` means that you tried to open a directory instead a file. Did you specify a direcotry path into the `-c` (or `--config`, `--configfile`)? It should be a config file name like `yuidoc.json`.

**Comment by krawalli** [comment]
No, it's a file.

After manual clearing the target (output) directory it's working again.

**Comment by okuryu** [comment]
Hmm, it's weird. Could you provide reproducible example? I'd like to take a look if I could have a repro.

**Comment by krawalli** [comment]
Sorry, i didn't take a look into that directory before i deleted it.
Tryed to reproduced it putting a filename with the outdir's name in it but it does not trigger that exception.

**Comment by okuryu** [comment]
Okay, I'm not able to reproduce it for now. Please let me know if it occurs for you again.
