### ISSUE TITLE
Throwing Error ENOTEMPTY & ENOENT!

### ISSUE THREAD

**Issue by iyogeshjoshi** [yui/yuidoc#333]
Hi I was trying to install yuidocjs from `npm` and everytime it is throwing this error. [here](https://gist.github.com/iyogeshjoshi/14a05368a814bbca389e) is the complete gist with thrown error also pasting the same here

```shell
$ sudo npm i yuidocjs -g
npm http GET https://registry.npmjs.org/yuidocjs
npm http 304 https://registry.npmjs.org/yuidocjs
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/markdown-it
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/yui
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/markdown-it
npm http 304 https://registry.npmjs.org/yui
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/content-disposition/0.5.0
npm http GET https://registry.npmjs.org/content-type
npm http GET https://registry.npmjs.org/cookie/0.1.2
npm http GET https://registry.npmjs.org/cookie-signature/1.0.6
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/depd
npm http GET https://registry.npmjs.org/escape-html/1.0.1
npm http GET https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/finalhandler/0.3.4
npm http GET https://registry.npmjs.org/fresh/0.2.4
npm http GET https://registry.npmjs.org/merge-descriptors/1.0.0
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/path-to-regexp/0.1.3
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/qs/2.4.1
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/send/0.12.2
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/vary
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/linkify-it
npm http GET https://registry.npmjs.org/uc.micro
npm http GET https://registry.npmjs.org/mdurl
npm http 304 https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/accepts
npm http 304 https://registry.npmjs.org/content-type
npm http 304 https://registry.npmjs.org/cookie/0.1.2
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/depd
npm http 304 https://registry.npmjs.org/content-disposition/0.5.0
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.6
npm http 304 https://registry.npmjs.org/finalhandler/0.3.4
npm http 304 https://registry.npmjs.org/etag
npm http 304 https://registry.npmjs.org/fresh/0.2.4
npm http 304 https://registry.npmjs.org/escape-html/1.0.1
npm http 304 https://registry.npmjs.org/merge-descriptors/1.0.0
npm http 304 https://registry.npmjs.org/methods
npm http 304 https://registry.npmjs.org/on-finished
npm http 304 https://registry.npmjs.org/parseurl
npm http 304 https://registry.npmjs.org/proxy-addr
npm http 304 https://registry.npmjs.org/path-to-regexp/0.1.3
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/qs/2.4.1
npm http 304 https://registry.npmjs.org/type-is
npm http 304 https://registry.npmjs.org/serve-static
npm http 304 https://registry.npmjs.org/send/0.12.2
npm http 304 https://registry.npmjs.org/vary
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/linkify-it
npm http 304 https://registry.npmjs.org/utils-merge/1.0.0
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/mdurl
npm http 304 https://registry.npmjs.org/uc.micro
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/crc/3.2.1
npm http GET https://registry.npmjs.org/ee-first/1.1.0
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/negotiator/0.5.1
npm http GET https://registry.npmjs.org/media-typer/0.3.0
npm http GET https://registry.npmjs.org/forwarded
npm http GET https://registry.npmjs.org/ipaddr.js/0.1.9
npm http GET https://registry.npmjs.org/destroy/1.0.3
npm http GET https://registry.npmjs.org/mime/1.3.4
npm http GET https://registry.npmjs.org/ms/0.7.0
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/sprintf-js
npm http 304 https://registry.npmjs.org/crc/3.2.1
npm http 304 https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/forwarded
npm http 304 https://registry.npmjs.org/negotiator/0.5.1
npm http 304 https://registry.npmjs.org/media-typer/0.3.0
npm http 304 https://registry.npmjs.org/ee-first/1.1.0
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/ipaddr.js/0.1.9
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/mime/1.3.4
npm http 304 https://registry.npmjs.org/ms/0.7.0
npm http 304 https://registry.npmjs.org/destroy/1.0.3
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/sprintf-js
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/mime-db
npm ERR! tar.unpack untar error /home/iyogeshjoshi/.npm/request/2.40.0/package.tgz
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yuidocjs/node_modules/yui/node_modules/request/request.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
 
npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "i" "yuidocjs" "-g"
npm ERR! cwd /var/www/learnise/app
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /usr/local/lib/node_modules/yuidocjs/node_modules/yui/node_modules/request/request.js
npm ERR! fstream_path /usr/local/lib/node_modules/yuidocjs/node_modules/yui/node_modules/request/request.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/yuidocjs/node_modules/markdown-it/node_modules/argparse/node_modules/lodash/collection'
npm ERR! error rolling back  yuidocjs@0.6.0 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/yuidocjs/node_modules/markdown-it/node_modules/argparse/node_modules/lodash/collection']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/yuidocjs/node_modules/markdown-it/node_modules/argparse/node_modules/lodash/collection' }
npm ERR! Error: unexpected eof
npm ERR!     at decorate (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/abstract.js:67:36)
npm ERR!     at Extract.Abstract.error (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/abstract.js:61:12)
npm ERR!     at Extract._streamEnd (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extract.js:75:22)
npm ERR!     at BlockStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:50:8)
npm ERR!     at BlockStream.EventEmitter.emit (events.js:92:17)
npm ERR!     at BlockStream._emitChunk (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:203:10)
npm ERR!     at BlockStream.resume (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
npm ERR!     at Extract.Reader.resume (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js:253:34)
npm ERR!     at Entry.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:256:8)
npm ERR!     at Entry.EventEmitter.emit (events.js:92:17)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
 
npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "i" "yuidocjs" "-g"
npm ERR! cwd /var/www/learnise/app
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! fstream_class Extract
npm ERR! fstream_stack Extract._streamEnd (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extract.js:75:22)
npm ERR! fstream_stack BlockStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:50:8)
npm ERR! fstream_stack BlockStream.EventEmitter.emit (events.js:92:17)
npm ERR! fstream_stack BlockStream._emitChunk (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:203:10)
npm ERR! fstream_stack BlockStream.resume (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
npm ERR! fstream_stack Extract.Reader.resume (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js:253:34)
npm ERR! fstream_stack Entry.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:256:8)
npm ERR! fstream_stack Entry.EventEmitter.emit (events.js:92:17)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yuidocjs/node_modules/express/node_modules/accepts/node_modules/mime-types/node_modules/mime-db/db.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
 
npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "i" "yuidocjs" "-g"
npm ERR! cwd /var/www/learnise/app
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /usr/local/lib/node_modules/yuidocjs/node_modules/express/node_modules/accepts/node_modules/mime-types/node_modules/mime-db/db.json
npm ERR! fstream_path /usr/local/lib/node_modules/yuidocjs/node_modules/express/node_modules/accepts/node_modules/mime-types/node_modules/mime-db/db.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/learnise/app/npm-debug.log
npm ERR! not ok code 0
```

I'm using ubuntu machine. please check :)

**Comment by okuryu** [comment]
Could you try this?
```sh
$ npm cache clean
```

**Comment by iyogeshjoshi** [comment]
@okuryu hey yes it worked :+1: . Can you explain what was the problem?

**Comment by okuryu** [comment]
I've just searched your error message and found a similar issue.
https://github.com/npm/npm/issues/5133

**Comment by iyogeshjoshi** [comment]
@okuryu thanks :) I think I was looking in wrong places.
