### ISSUE TITLE
--lint error - An uncaught YUIDoc error has occurred, stack trace given below

### ISSUE THREAD

**Issue by CoHyper** [yui/yuidoc#403]
> OS X El Capitan 10.11.3

***reproduce***
* run ```$ ./node_modules/.bin/yuidoc source/core/ --lint```
* YUIDoc found 1 lint errors in your docs
* fix it
* run again ```$ ./node_modules/.bin/yuidoc source/core/ --lint```

```
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: Error: Running YUIDoc returns null.
    at Object.<anonymous> (/Users/cohyper/_work/manni/node_modules/yuidocjs/lib/cli.js:38:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
error: --------------------------------------------------------------------------
error: Node.js version: v4.2.1
error: YUI version: 3.18.1
error: YUIDoc version: 0.10.0
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------
```

***expected for the result***
* YUIDoc found 0 lint errors in your docs
* And  generate the documentations

**Comment by Turbo87** [comment]
this seems to have been broken by https://github.com/yui/yuidoc/pull/348/files#diff-f8849ae9f0614ba9464fdd14c2d98dc0
