### ISSUE TITLE
html is not defined

### ISSUE THREAD

**Issue by fendoude007** [yui/yuidoc#415]
why i use yuidoc cause an err
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: 
ReferenceError: html is not defined
    at /usr/local/lib/node_modules/smartdoc/smartDoc.js:287:18
    at prepare (/usr/local/lib/node_modules/smartdoc/node_modules/yuidocjs/lib/utils.js:218:5)
    at render (/usr/local/lib/node_modules/smartdoc/smartDoc.js:246:11)
    at Object.Y.DocBuilder.writeDemo (/usr/local/lib/node_modules/smartdoc/smartDoc.js:188:13)
    at /usr/local/lib/node_modules/smartdoc/smartDoc.js:86:21
    at null.<anonymous> (/usr/local/lib/node_modules/smartdoc/node_modules/yuidocjs/lib/builder.js:1591:39)
    at Object.e.Parallel.test (/usr/local/lib/node_modules/smartdoc/node_modules/yuidocjs/node_modules/yui/parallel/parallel-min.js:2:479)
    at /usr/local/lib/node_modules/smartdoc/node_modules/yuidocjs/node_modules/yui/parallel/parallel-min.js:2:399
    at null.<anonymous> (/usr/local/lib/node_modules/smartdoc/node_modules/yuidocjs/lib/builder.js:1438:17)
    at Object.e.Parallel.test (/usr/local/lib/node_modules/smartdoc/node_modules/yuidocjs/node_modules/yui/parallel/parallel-min.js:2:479)
error: --------------------------------------------------------------------------
error: Node.js version: v4.4.5
error: YUI version: 3.9.1
error: YUIDoc version: 0.3.45
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------

**Comment by fendoude007** [comment]
I have resolved this problem thanks very much

**Comment by yuexushuang** [comment]
How did you fix it? @fendoude007 Please help me

**Comment by gongph** [comment]
+1 @fendoude007
