### ISSUE TITLE
yuidoc won't run on Mac with Apple Silicon

### ISSUE THREAD

**Issue by brettonw** [yui/yuidoc#455]
Homebrew on Ventura on Apple M1 silicon installs node modules in 

    /opt/homebrew/lib/node_modules/

instead of in 

    /usr/local/lib/node_modules/

Yuidoc is just not finding things correctly. I can't tell if its a homebrew problem, an npm problem, or a yuidoc problem. But the path to the theme is obviously incorrect in the error message:

     [exec] error: Error: Cannot find module '/Users/(my project path)/opt/homebrew/lib/node_modules/yuidoc-lucid-theme/helpers/helpers.js'
     [exec] Require stack:
     [exec] - /opt/homebrew/lib/node_modules/yuidocjs/lib/builder.js
     [exec] - /opt/homebrew/lib/node_modules/yuidocjs/node_modules/yui/yui-nodejs/yui-nodejs.js
     [exec] - /opt/homebrew/lib/node_modules/yuidocjs/node_modules/yui/index.js
     [exec] - /opt/homebrew/lib/node_modules/yuidocjs/lib/index.js
     [exec] - /opt/homebrew/lib/node_modules/yuidocjs/lib/cli.js
     [exec]     at Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
     [exec]     at Module._load (node:internal/modules/cjs/loader:872:27)
     [exec]     at Module.require (node:internal/modules/cjs/loader:1092:19)
     [exec]     at require (node:internal/modules/cjs/helpers:103:18)
     [exec]     at /opt/homebrew/lib/node_modules/yuidocjs/lib/builder.js:137:25
     [exec]     at Array.forEach (<anonymous>)
     [exec]     at Y.DocBuilder._addHelpers (/opt/homebrew/lib/node_modules/yuidocjs/lib/builder.js:133:21)
     [exec]     at new Y.DocBuilder (/opt/homebrew/lib/node_modules/yuidocjs/lib/builder.js:58:18)
     [exec]     at Object.<anonymous> (/opt/homebrew/lib/node_modules/yuidocjs/lib/cli.js:43:23)
     [exec]     at Module._compile (node:internal/modules/cjs/loader:1205:14)
     [exec] error: --------------------------------------------------------------------------
     [exec] error: Node.js version: v19.1.0
     [exec] error: YUI version: 3.18.1
     [exec] error: YUIDoc version: 0.10.2
     [exec] error: Please file all tickets here: http://github.com/yui/yuidoc/issues
     [exec] error: --------------------------------------------------------------------------
     [exec] Result: 1

**Comment by quinton-ashley** [comment]
It runs on my M1 macbook, try installing it with npm
